### ISSUE TITLE
Mtl file does not exist: ./modules/data/template.mtl

### ISSUE THREAD

**Issue by corranmac** [Qiulin-W/SAFA#1]
I believe I have copied over all the correct files however, I get the error
/usr/local/lib/python3.7/site-packages/pytorch3d/io/obj_io.py:533: UserWarning: Mtl file does not exist: ./modules/data/template.mtl

I don't see a template.mtl anywhere either/.

Full error:

/content/SAFA
/usr/local/lib/python3.7/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/usr/local/lib/python3.7/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
blend_scale:  1
creating the FLAME Decoder
  warnings.warn(f"Mtl file does not exist: {f}")
Traceback (most recent call last):
  File "animation_demo.py", line 208, in <module>
    generator, kp_detector, tdmm = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "animation_demo.py", line 44, in load_checkpoints
    checkpoint = torch.load(checkpoint_path)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by Qiulin-W** [comment]
Hi, 

The warning "Mtl file does not exist: {f}" appears in my case as well, but the code still works.
Your problem seems to be that the checkpoint is not loaded correctly...
