### ISSUE TITLE
No module named 'modules.flame_config'

### ISSUE THREAD

**Issue by KimoriFighting** [Qiulin-W/SAFA#2]
Did the author forget to upload it? Or is there another way to download?

**Comment by Qiulin-W** [comment]
Fixed, thx

**Comment by KimoriFighting** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我已经收到你的信息，会很快回复你的

**Comment by KimoriFighting** [comment]
Hello, is there a little problem with SAFA Model Checkpoint you provided? Why is there an error after I download it?

**Comment by KimoriFighting** [comment]
System tip: tar: It does not appear to be a tar archive
