### ISSUE TITLE
About checkpoint

### ISSUE THREAD

**Issue by winterplayer** [Qiulin-W/SAFA#8]
I download SAFA model checkpoint from [Google Drive](https://drive.google.com/drive/folders/1sXzcAf9mIK08WISz9tjYBocaoTSA3ts_?usp=sharing),and use data.pkl to the checkpoint.But there are some errors.
  File "/home/mpl/anaconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by VisionaryMind** [comment]
@winterplayer , this error will be seen if you extract the serialized TAR file and access the PKL directly. The checkpoint should reference the TAR directly: `./ckpt/final_3DV.tar`.

**Comment by winterplayer** [comment]
> 

Thank you！The error is disappeared.
