### ISSUE TITLE
Please advise on how to increase resolution

### ISSUE THREAD

**Issue by VisionaryMind** [Qiulin-W/SAFA#9]
First, I want to congratulate you on an ingenious paper. The idea of using FLAME with face alignment and masking is simply brilliant. I am getting very good results with your current code. However, I would like to ask if you could provide some brief advice on how to raise the resolution (e.g. from 256x256 to 512x512). I attempted to adjust settings in the code, but there were persistent tensor mismatch problems. I presume the dataset must be re-trained at higher resolution? Please advise, if you will have time.

**Comment by Qiulin-W** [comment]
Hi, 
thank for your interests to our paper. Regarding to increasing resolution,  you need to change the resolution of the rendered 3D reenactment and 3D face motion so that they can fit.

**Comment by VisionaryMind** [comment]
Unfortunately, it's not possible to re-train on adjusted 3D-re-enactment / face motion since the VoxCeleb dataset is no longer available. If you have a suggestion for another dataset which is still publicly accessible online, please let me know. It appears Google / Youtube blocks downloads with the youtube-dl utility, regardless of origin network (e.g. VPN). I have not been able to find the videos in archived format.

**Comment by VisionaryMind** [comment]
@Qiulin-W, thank you for the explanation. This will require a re-training of the model using the VoxCeleb dataset. We have tried to download it using the Youtube URLs, but even with 32 workers, this will be a ~20 day task. Would you be so kind as to provide the dataset (temporarily) for download? The re-training is expected to take much time, and having a faster way to procure the data would speed up the process. Thank you!

**Comment by Qiulin-W** [comment]
> 

Sorry we can't provide the dataset.
